### ISSUE TITLE
es6 support

### ISSUE THREAD

**Issue by Guria** [szarouski/sourcejs-react#7]
allow to use es6 syntax for react components

**Comment by webuniverseio** [comment]
Hi @Guria, you [should](https://github.com/szarouski/sourcejs-react/blob/master/core/middleware/index.js#L3) [be](https://github.com/szarouski/sourcejs-react/blob/master/core/middleware/index.js#L36) able to do so already. [Here is a list](https://kangax.github.io/compat-table/es6/#jsx) of officially supported features. Let me know if that is not exactly what you're asking about.

**Comment by webuniverseio** [comment]
@Guria, I assume the issue is resolved?

**Comment by Guria** [comment]
Haven't tried again, but I wasn't able to use es6 import syntax

**Comment by webuniverseio** [comment]
I see, I'll take a look at what could be done about it.

**Comment by webuniverseio** [comment]
Hi @Guria, I added support via babel in [develop](https://github.com/szarouski/sourcejs-react/tree/develop) branch. At the moment I'm doing beta testing on my existing app. I will also need to update documentation to describe how to configure support via `user/options.js`. I hope to release next version on Monday.

**Comment by webuniverseio** [comment]
sourcejs-react [now](https://www.npmjs.com/package/sourcejs-react) transforms jsx via babel. Take a look at [options](https://github.com/szarouski/sourcejs-react#options) section to see how to configure babel options. Let me know if you run into any issues.
