### ISSUE TITLE
Watch for external imports

### ISSUE THREAD

**Issue by biirus** [szarouski/sourcejs-react#8]
Hi, I'm trying to use sourcejs-react and I've stuck with some ussie.

For example: I have a JSX spec (**index.jsx**), it uses another component (**/library/components/sidenav/Sidenav.js**). 
I import it in **index.js** 

``` javascript
var Sidenav = require('../path/to/Sidenav.js');
```

It compiles well, but when I change **Sidenav.js** and refresh the spec page, it doesn't update. Only when I restart whole sourcejs app, all changes apply.

May be I should use some setting or smth else?

**Comment by webuniverseio** [comment]
Hi @biirus, currently sourcejs-react only clears cache for *.jsx files, but with version that I have in develop branch you can specify glob patters via `refreshCachePatterns` property in plugins options (inside `user/options.js`). I'll merge develop in master and publish it to npm in a few days, just need to find a little bit of time to update documentation :). Stay tuned.

**Comment by webuniverseio** [comment]
[sourcejs-react v2](https://www.npmjs.com/package/sourcejs-react) gives you an option to cache bust custom paths via `refreshCachePatterns`. Please take a look at [options section](https://github.com/szarouski/sourcejs-react#options) to see how to configure it. Let me know if you run into any issues.
